import { Color3 } from "@babylonjs/core/Maths/math.color";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { Texture } from "@babylonjs/core/Materials/Textures/texture";
import { TransformNode } from "@babylonjs/core/Meshes/transformNode";
import type { AbstractMesh } from "@babylonjs/core/Meshes/abstractMesh";
import type { Scene } from "@babylonjs/core/scene";
import type { MechaAction, MechaProfile, SpecialDefinition } from "./types";

type FramePart = "torso" | "helmet" | "visor" | "shoulderLeft" | "shoulderRight" | "armFront" | "armBack" | "handFront" | "handBack" | "weapon" | "core" | "legLeft" | "legRight" | "footLeft" | "footRight";
export interface MechaConfig { id: "player" | "enemy"; startX: number; direction: 1 | -1; textureUrl: string; profile: MechaProfile; }

const MOVING_PARTS = new Set<FramePart>(["helmet", "visor", "core", "shoulderLeft", "shoulderRight", "armFront", "armBack", "handFront", "handBack", "weapon"]);

export class Mecha {
  readonly root: TransformNode;
  readonly direction: 1 | -1;
  readonly id: "player" | "enemy";
  label: string;
  hp: number;
  action: MechaAction = "idle";
  private profile: MechaProfile;
  private actionUntil = 0;
  private actionStarted = 0;
  private cooldownUntil = 0;
  private impactAt = 0;
  private impactResolved = false;
  private readonly sprite: AbstractMesh;
  private readonly spriteMaterial: StandardMaterial;
  private readonly shadow: AbstractMesh;
  private readonly strike: AbstractMesh;
  private readonly shield: AbstractMesh;
  private readonly flair: AbstractMesh;
  private readonly enginePods: AbstractMesh[] = [];
  private readonly engineFlares: AbstractMesh[] = [];
  private readonly engineMaterials: StandardMaterial[] = [];
  private readonly parts = {} as Record<FramePart, AbstractMesh>;
  private readonly basePose: Record<FramePart, [number, number]> = {
    torso: [0, 0.04], helmet: [0.12, 0.75], visor: [0.12, 0.75], shoulderLeft: [-0.65, 0.38], shoulderRight: [0.65, 0.38], armFront: [0.77, -0.18], armBack: [-0.77, -0.18], handFront: [0.95, -0.58], handBack: [-0.94, -0.53], weapon: [1.26, -0.57], core: [0.12, 0.03], legLeft: [-0.34, -0.86], legRight: [0.34, -0.86], footLeft: [-0.38, -1.34], footRight: [0.38, -1.34],
  };
  private accent: Color3;
  private flare: Color3;
  private moveAmount = 0;
  private velocity = 0;
  private hitPulseUntil = 0;
  private guardPulseUntil = 0;
  private recoil = 0;
  private boostUntil = 0;
  private boostCooldownUntil = 0;
  private specialUntil = 0;
  private specialCooldownUntil = 0;
  private specialImpactAt = 0;
  private specialImpactResolved = false;
  private fortifiedUntil = 0;

  constructor(scene: Scene, config: MechaConfig) {
    this.id = config.id; this.direction = config.direction; this.profile = config.profile; this.label = config.profile.label; this.hp = config.profile.maxHp; this.accent = Color3.FromHexString(config.profile.accent); this.flare = Color3.FromHexString(config.profile.flare);
    this.root = new TransformNode(`${config.id}-root`, scene); this.root.position.set(config.startX, -1.2, 0);
    this.shadow = MeshBuilder.CreateDisc(`${config.id}-shadow`, { radius: 1.1, tessellation: 16 }, scene); this.shadow.parent = this.root; this.shadow.position.set(0, -1.45, 0.05); this.shadow.scaling.y = 0.24;
    const shadowMaterial = new StandardMaterial(`${config.id}-shadow-material`, scene); shadowMaterial.diffuseColor = new Color3(0.02, 0.03, 0.03); shadowMaterial.alpha = 0.45; shadowMaterial.disableLighting = true; this.shadow.material = shadowMaterial;
    this.sprite = MeshBuilder.CreatePlane(`${config.id}-sprite`, { width: 2.85, height: 2.85 }, scene); this.sprite.parent = this.root; this.sprite.position.set(0, 0, -0.18);
    this.spriteMaterial = new StandardMaterial(`${config.id}-sprite-material`, scene); const spriteTexture = new Texture(config.textureUrl, scene, true, false); spriteTexture.hasAlpha = true; this.spriteMaterial.diffuseTexture = spriteTexture; this.spriteMaterial.useAlphaFromDiffuseTexture = true; this.spriteMaterial.alpha = 0.94; this.spriteMaterial.specularColor = Color3.Black(); this.spriteMaterial.diffuseColor = Color3.White(); this.spriteMaterial.emissiveColor = new Color3(0.35, 0.35, 0.35); this.spriteMaterial.backFaceCulling = false; this.sprite.material = this.spriteMaterial;
    this.shield = MeshBuilder.CreateDisc(`${config.id}-shield`, { radius: 1.55, tessellation: 8 }, scene); this.shield.parent = this.root; this.shield.position.set(config.direction * 0.52, 0, -0.1); const shieldMaterial = new StandardMaterial(`${config.id}-shield-material`, scene); shieldMaterial.diffuseColor = this.accent; shieldMaterial.emissiveColor = this.accent.scale(0.8); shieldMaterial.alpha = 0.28; shieldMaterial.disableLighting = true; this.shield.material = shieldMaterial; this.shield.isVisible = false;
    this.strike = MeshBuilder.CreatePlane(`${config.id}-strike`, { width: 1.72, height: 0.22 }, scene); this.strike.parent = this.root; this.strike.position.set(config.direction * 1.55, 0.08, -0.4); const strikeMaterial = new StandardMaterial(`${config.id}-strike-material`, scene); strikeMaterial.diffuseColor = this.flare; strikeMaterial.emissiveColor = this.flare; strikeMaterial.alpha = 0.88; strikeMaterial.disableLighting = true; this.strike.material = strikeMaterial; this.strike.isVisible = false;
    this.flair = MeshBuilder.CreateDisc(`${config.id}-flair`, { radius: 0.5, tessellation: 8 }, scene); this.flair.parent = this.root; this.flair.position.set(config.direction * 1.34, 0.15, -0.35); const flairMaterial = new StandardMaterial(`${config.id}-flair-material`, scene); flairMaterial.diffuseColor = this.flare; flairMaterial.emissiveColor = this.flare; flairMaterial.alpha = 0.86; flairMaterial.disableLighting = true; this.flair.material = flairMaterial; this.flair.isVisible = false;
    const shellMaterial = new StandardMaterial(`${config.id}-shell`, scene); shellMaterial.diffuseColor = this.accent; shellMaterial.emissiveColor = this.accent.scale(0.22); const jointMaterial = new StandardMaterial(`${config.id}-joint`, scene); jointMaterial.diffuseColor = Color3.FromHexString("#18201f"); jointMaterial.emissiveColor = Color3.FromHexString("#071111"); const signalMaterial = new StandardMaterial(`${config.id}-signal`, scene); signalMaterial.diffuseColor = this.flare; signalMaterial.emissiveColor = this.flare; signalMaterial.disableLighting = true;
    const part = (name: FramePart, width: number, height: number, material: StandardMaterial) => { const mesh = MeshBuilder.CreateBox(`${config.id}-${name}`, { width, height, depth: 0.18 }, scene); mesh.parent = this.root; const [x, y] = this.basePose[name]; mesh.position.set(x * (MOVING_PARTS.has(name) ? this.direction : 1), y, -0.63); mesh.material = material; this.parts[name] = mesh; };
    part("torso", 1.05, 0.94, shellMaterial); part("helmet", 0.62, 0.44, shellMaterial); part("visor", 0.42, 0.09, signalMaterial); part("shoulderLeft", 0.48, 0.34, shellMaterial); part("shoulderRight", 0.48, 0.34, shellMaterial); part("armFront", 0.34, 0.82, jointMaterial); part("armBack", 0.3, 0.74, jointMaterial); part("handFront", 0.28, 0.25, shellMaterial); part("handBack", 0.24, 0.22, shellMaterial); part("weapon", 0.78, 0.12, signalMaterial); part("core", 0.22, 0.22, signalMaterial); part("legLeft", 0.38, 0.88, jointMaterial); part("legRight", 0.38, 0.88, jointMaterial); part("footLeft", 0.58, 0.2, shellMaterial); part("footRight", 0.58, 0.2, shellMaterial);
    for (const index of [-1, 1]) { const pod = MeshBuilder.CreateBox(`${config.id}-engine-pod-${index}`, { width: 0.28, height: 0.48, depth: 0.18 }, scene); pod.parent = this.root; pod.position.set(-config.direction * 0.68, index * 0.34 - 0.12, -0.55); pod.material = jointMaterial; this.enginePods.push(pod); const engine = MeshBuilder.CreatePlane(`${config.id}-engine-flare-${index}`, { width: 0.56, height: 0.22 }, scene); engine.parent = this.root; engine.position.set(-config.direction * 1.06, index * 0.34 - 0.12, -0.58); const engineMaterial = new StandardMaterial(`${config.id}-engine-material-${index}`, scene); engineMaterial.diffuseColor = this.flare; engineMaterial.emissiveColor = this.flare; engineMaterial.alpha = 0.76; engineMaterial.disableLighting = true; engine.material = engineMaterial; this.engineFlares.push(engine); this.engineMaterials.push(engineMaterial); }
    this.setProfile(config.profile);
  }

  get x() { return this.root.position.x; } get maxHp() { return this.profile.maxHp; } get speed() { return this.profile.speed; } get strikeDamage() { return this.profile.strikeDamage; } get special() { return this.profile.special; } get isDown() { return this.action === "down"; } get isGuarding() { return this.action === "guard"; } get canStrike() { return !this.isDown && this.action !== "damaged" && this.action !== "special"; } get guardMultiplier() { return this.profile.guardMultiplier; } getSpecialCooldown(now: number) { return Math.max(0, this.specialCooldownUntil - now); }
  setProfile(profile: MechaProfile) { this.profile = profile; this.label = profile.label; this.accent = Color3.FromHexString(profile.accent); this.flare = Color3.FromHexString(profile.flare); this.root.scaling.setAll(profile.frameScale); this.parts.torso.scaling.x = profile.chassis === "bulwark" || profile.chassis === "brute" ? 1.22 : profile.chassis === "scout" || profile.chassis === "phantom" ? 0.83 : 1; this.parts.shoulderLeft.scaling.setAll(profile.chassis === "heavy" || profile.chassis === "bulwark" ? 1.24 : 1); this.parts.shoulderRight.scaling.setAll(profile.chassis === "heavy" || profile.chassis === "bulwark" ? 1.24 : 1); this.engineMaterials.forEach((material) => { material.diffuseColor = this.flare; material.emissiveColor = this.flare; }); }
  move(amount: number, _delta: number, now: number) { if (this.isDown || this.action === "strike" || this.action === "damaged") { this.moveAmount = 0; return; } this.moveAmount = Math.max(-1, Math.min(1, amount)); if (amount === 0) { if (this.action === "move") this.beginAction("idle", now); return; } if (this.action !== "move") this.beginAction("move", now); }
  setGuard(active: boolean, now: number) { if (this.isDown || this.action === "strike" || this.action === "damaged") return; if (active && this.action !== "guard") this.beginAction("guard", now); if (!active && this.action === "guard") this.beginAction(this.moveAmount === 0 ? "idle" : "move", now); }
  boost(amount: number, now: number) { if (this.isDown || this.action === "strike" || this.action === "damaged" || now < this.boostCooldownUntil) return false; const direction = amount === 0 ? this.direction : Math.sign(amount); this.moveAmount = direction; this.velocity = direction * this.speed * 2.35; this.boostUntil = now + 0.24; this.boostCooldownUntil = now + 0.72; this.beginAction("move", now); return true; }
  startSpecial(now: number) { const special = this.profile.special; if (!special || this.isDown || this.action === "strike" || this.action === "special" || this.action === "damaged" || now < this.specialCooldownUntil) return false; this.moveAmount = 0; this.velocity *= 0.2; const duration = special.kind === "slam" ? 0.78 : special.kind === "volley" ? 0.7 : 0.62; this.beginAction("special", now, duration); this.specialUntil = now + duration; this.specialCooldownUntil = now + special.cooldown; this.specialImpactAt = now + (special.kind === "slam" ? 0.42 : special.kind === "volley" ? 0.34 : 0.28); this.specialImpactResolved = false; if (special.kind === "fortify") this.fortifiedUntil = now + 0.84; return true; }
  startStrike(now: number) { if (!this.canStrike || now < this.cooldownUntil) return false; this.moveAmount = 0; this.velocity *= 0.46; this.beginAction("strike", now, 0.54); this.cooldownUntil = now + 0.76; this.impactAt = now + 0.23; this.impactResolved = false; return true; }
  needsImpact(now: number) { if (this.action !== "strike" || this.impactResolved || now < this.impactAt) return false; this.impactResolved = true; return true; }
  needsSpecialImpact(now: number) { if (this.action !== "special" || this.specialImpactResolved || now < this.specialImpactAt) return false; this.specialImpactResolved = true; return true; }
  specialApproach(targetX: number, range: number) { this.root.position.x = Math.max(-6.1, Math.min(6.1, targetX - this.direction * Math.min(1.7, Math.max(0.85, range * 0.38)))); }
  receiveDamage(damage: number, now: number) { const fortified = now < this.fortifiedUntil; const guarded = this.isGuarding || fortified; const multiplier = fortified ? Math.min(this.profile.guardMultiplier, 0.1) : this.profile.guardMultiplier; const resolvedDamage = guarded ? Math.max(2, Math.ceil(damage * multiplier)) : damage; this.hp = Math.max(0, this.hp - resolvedDamage); if (guarded) { this.guardPulseUntil = now + 0.22; this.recoil = -this.direction * 0.12; } else { this.hitPulseUntil = now + 0.24; this.recoil = -this.direction * 0.22; if (this.hp === 0) this.beginAction("down", now, Number.POSITIVE_INFINITY); else this.beginAction("damaged", now, 0.32); } return { guarded, damage: resolvedDamage }; }
  reset(x: number, now: number) { this.hp = this.profile.maxHp; this.moveAmount = 0; this.velocity = 0; this.recoil = 0; this.hitPulseUntil = 0; this.guardPulseUntil = 0; this.boostUntil = 0; this.boostCooldownUntil = 0; this.specialUntil = 0; this.specialCooldownUntil = 0; this.specialImpactResolved = false; this.fortifiedUntil = 0; this.beginAction("idle", now); this.cooldownUntil = 0; this.root.position.set(x, -1.2, 0); }
  update(now: number, delta: number) { this.updateLocomotion(delta); if (this.action !== "down" && this.actionUntil && now > this.actionUntil) this.beginAction(this.moveAmount === 0 ? "idle" : "move", now); this.applyPose(now); const specialGuard = this.action === "special" && this.profile.special?.kind === "fortify"; this.shield.isVisible = this.action === "guard" || specialGuard; this.shield.rotation.z += delta * 1.35; const guardPulse = now < this.guardPulseUntil; this.shield.scaling.setAll(guardPulse ? 1.22 : specialGuard ? 1.32 : this.action === "guard" ? 1 + Math.sin((now - this.actionStarted) * 10) * 0.055 : 0.94); const specialActive = this.action === "special" && now > this.specialImpactAt - 0.1 && now < this.specialImpactAt + 0.22; this.strike.isVisible = (this.action === "strike" && now > this.impactAt - 0.075 && now < this.impactAt + 0.16) || specialActive; this.flair.isVisible = this.strike.isVisible; this.strike.scaling.x = this.strike.isVisible ? (specialActive ? 1.45 : 0.82) + Math.min(1, Math.abs(this.velocity) / Math.max(0.1, this.speed)) * 0.25 : 0.5; const travel = Math.min(1, Math.abs(this.velocity) / Math.max(0.1, this.speed)); const output = this.action === "down" ? 0 : now < this.boostUntil ? 2.45 : this.action === "special" ? 2.16 : this.action === "move" ? 0.96 + travel * 0.55 : this.action === "strike" ? 1.55 : this.action === "guard" ? 0.62 : 0.58 + Math.sin(now * 6) * 0.12; this.engineFlares.forEach((flare, index) => { flare.isVisible = output > 0; flare.scaling.x = 0.52 + output * (0.96 + index * 0.1); flare.scaling.y = 0.48 + output * 0.52; }); this.spriteMaterial.emissiveColor = now < this.hitPulseUntil ? this.flare.scale(0.76) : guardPulse ? this.accent.scale(0.78) : this.action === "special" ? this.flare.scale(0.9) : now < this.boostUntil ? this.flare.scale(0.72) : this.action === "guard" ? this.accent.scale(0.2) : new Color3(0.12, 0.12, 0.12); }
  private updateLocomotion(delta: number) { const target = this.action === "move" ? this.moveAmount * this.speed : 0; const response = target === 0 ? 11 : 16; this.velocity += (target - this.velocity) * Math.min(1, delta * response); if (Math.abs(this.velocity) < 0.008) this.velocity = 0; this.root.position.x = Math.max(-6.25, Math.min(6.25, this.root.position.x + this.velocity * delta)); this.recoil *= Math.pow(0.0005, delta); this.root.position.x += this.recoil; }
  private beginAction(action: MechaAction, now: number, duration = 0) { this.action = action; this.actionStarted = now; this.actionUntil = duration ? now + duration : 0; }
  private resetPose() { (Object.keys(this.parts) as FramePart[]).forEach((name) => { const [x, y] = this.basePose[name]; const directional = MOVING_PARTS.has(name) ? this.direction : 1; const part = this.parts[name]; part.position.x = x * directional; part.position.y = y; part.rotation.z = 0; if (name !== "torso" && name !== "shoulderLeft" && name !== "shoulderRight") part.scaling.setAll(1); }); this.root.rotation.z = 0; this.sprite.position.set(0, 0, -0.18); this.strike.position.set(this.direction * 1.55, 0.08, -0.4); this.strike.rotation.z = this.direction === 1 ? -0.18 : 0.18; }
  private applyPose(now: number) { this.resetPose(); const parts = this.parts; const elapsed = now - this.actionStarted; const bob = Math.sin(now * 6.5) * 0.025; if (this.action === "idle") { parts.torso.position.y += bob; parts.helmet.position.y += bob * 1.25; parts.core.scaling.setAll(0.91 + (Math.sin(now * 5) + 1) * 0.09); parts.armFront.rotation.z = -this.direction * 0.07 + Math.sin(now * 3) * 0.035; parts.weapon.rotation.z = -this.direction * 0.08; }
    else if (this.action === "move") { const stride = Math.sin(elapsed * 15); const lean = Math.max(-0.12, Math.min(0.12, this.velocity / Math.max(0.1, this.speed) * 0.1)); this.root.rotation.z = -this.direction * lean; parts.legLeft.rotation.z = stride * 0.28; parts.legRight.rotation.z = -stride * 0.28; parts.footLeft.position.y += Math.max(0, stride) * 0.075; parts.footRight.position.y += Math.max(0, -stride) * 0.075; parts.armFront.rotation.z = -this.direction * (stride * 0.24 + 0.08); parts.armBack.rotation.z = this.direction * (stride * 0.2 - 0.05); parts.handFront.position.y += -stride * 0.09; parts.handBack.position.y += stride * 0.07; parts.weapon.rotation.z = -this.direction * (0.18 + stride * 0.12); this.sprite.position.y = Math.abs(stride) * 0.065; }
    else if (this.action === "strike") { const phase = Math.min(1, elapsed / 0.54); if (phase < 0.28) { const wind = phase / 0.28; this.root.rotation.z = -this.direction * (0.07 + wind * 0.1); parts.armFront.position.x -= this.direction * (0.12 + wind * 0.26); parts.armFront.rotation.z = this.direction * (0.22 + wind * 0.22); parts.handFront.position.x -= this.direction * (0.13 + wind * 0.28); parts.weapon.position.x -= this.direction * (0.16 + wind * 0.35); parts.weapon.rotation.z = this.direction * (0.35 + wind * 0.46); parts.legLeft.rotation.z = this.direction * 0.1; }
      else if (phase < 0.62) { const thrust = (phase - 0.28) / 0.34; const punch = Math.sin(thrust * Math.PI * 0.5); this.root.rotation.z = this.direction * 0.09 * punch; parts.armFront.position.x += this.direction * (0.48 + punch * 0.45); parts.armFront.rotation.z = -this.direction * (0.55 + punch * 0.32); parts.handFront.position.x += this.direction * (0.54 + punch * 0.47); parts.handFront.position.y -= punch * 0.08; parts.weapon.position.x += this.direction * (0.72 + punch * 0.57); parts.weapon.rotation.z = -this.direction * (0.45 + punch * 0.37); parts.armBack.rotation.z = this.direction * 0.18; parts.core.scaling.setAll(1.08 + punch * 0.23); this.sprite.position.x = this.direction * punch * 0.18; this.strike.position.x += this.direction * punch * 0.34; }
      else { const recover = (phase - 0.62) / 0.38; this.root.rotation.z = this.direction * 0.08 * (1 - recover); parts.armFront.position.x += this.direction * (0.45 * (1 - recover)); parts.armFront.rotation.z = -this.direction * (0.52 * (1 - recover)); parts.handFront.position.x += this.direction * (0.46 * (1 - recover)); parts.weapon.position.x += this.direction * (0.64 * (1 - recover)); parts.weapon.rotation.z = -this.direction * (0.45 * (1 - recover)); }
    } else if (this.action === "special") { const special: SpecialDefinition | undefined = this.profile.special; const phase = Math.min(1, elapsed / Math.max(0.62, this.specialUntil - this.actionStarted)); const surge = Math.sin(Math.min(1, phase * 1.55) * Math.PI); if (special?.kind === "lunge") { this.root.rotation.z = this.direction * (0.08 + surge * 0.11); parts.armFront.position.x += this.direction * (0.48 + surge * 0.86); parts.handFront.position.x += this.direction * (0.54 + surge * 0.96); parts.weapon.position.x += this.direction * (0.72 + surge * 1.02); parts.weapon.rotation.z = -this.direction * (0.25 + surge * 0.78); parts.legLeft.rotation.z = this.direction * 0.22; this.sprite.position.x = this.direction * surge * 0.33; }
      else if (special?.kind === "fortify") { this.root.rotation.z = -this.direction * 0.08; parts.armFront.position.x += this.direction * 0.6; parts.armFront.position.y += 0.19; parts.armFront.rotation.z = -this.direction * 0.82; parts.handFront.position.x += this.direction * 0.65; parts.handFront.position.y += 0.22; parts.weapon.position.x += this.direction * 0.42; parts.weapon.position.y += 0.38; parts.weapon.rotation.z = -this.direction * 1.14; parts.armBack.rotation.z = this.direction * 0.42; parts.legLeft.rotation.z = this.direction * 0.16; parts.legRight.rotation.z = -this.direction * 0.16; }
      else if (special?.kind === "blink") { const blink = phase < 0.42 ? phase / 0.42 : 1 - (phase - 0.42) / 0.58; this.sprite.position.x = this.direction * blink * 0.54; this.sprite.position.y = Math.sin(phase * Math.PI) * 0.14; this.root.rotation.z = this.direction * (0.12 + blink * 0.16); parts.armFront.position.x += this.direction * (0.4 + blink * 0.64); parts.handFront.position.x += this.direction * (0.42 + blink * 0.72); parts.weapon.position.x += this.direction * (0.68 + blink * 0.86); parts.weapon.rotation.z = -this.direction * (0.42 + blink * 0.7); parts.legLeft.rotation.z = -this.direction * 0.24; parts.legRight.rotation.z = this.direction * 0.24; }
      else if (special?.kind === "slam") { const drop = phase < 0.52 ? phase / 0.52 : 1 - (phase - 0.52) / 0.48; this.sprite.position.y = Math.sin(Math.min(phase / 0.52, 1) * Math.PI * 0.5) * 0.28; this.root.rotation.z = this.direction * (0.06 - drop * 0.17); parts.armFront.position.x += this.direction * 0.38; parts.armFront.rotation.z = this.direction * (0.28 + drop * 1.12); parts.handFront.position.y -= drop * 0.48; parts.weapon.position.x += this.direction * 0.28; parts.weapon.position.y -= drop * 0.56; parts.weapon.rotation.z = this.direction * (0.22 + drop * 1.18); parts.legLeft.rotation.z = this.direction * 0.26; parts.legRight.rotation.z = -this.direction * 0.26; }
      else if (special?.kind === "volley") { const pulse = Math.sin(phase * Math.PI * 2) * 0.13; this.root.rotation.z = this.direction * pulse; parts.armFront.position.x += this.direction * (0.5 + surge * 0.45); parts.armFront.rotation.z = -this.direction * (0.55 + surge * 0.35); parts.armBack.position.x -= this.direction * (0.36 + surge * 0.28); parts.armBack.rotation.z = this.direction * (0.47 + surge * 0.32); parts.handFront.position.x += this.direction * (0.56 + surge * 0.45); parts.handBack.position.x -= this.direction * (0.36 + surge * 0.28); parts.weapon.position.x += this.direction * (0.76 + surge * 0.56); parts.weapon.rotation.z = -this.direction * (0.18 + surge * 0.38); parts.core.scaling.setAll(1.2 + surge * 0.3); }
    } else if (this.action === "guard") { const brace = 0.09 + Math.sin(elapsed * 10) * 0.02; this.root.rotation.z = -this.direction * brace; parts.armFront.position.x += this.direction * 0.42; parts.armFront.position.y += 0.12; parts.armFront.rotation.z = -this.direction * 0.58; parts.handFront.position.x += this.direction * 0.52; parts.handFront.position.y += 0.2; parts.handFront.rotation.z = -this.direction * 0.32; parts.weapon.position.x += this.direction * 0.28; parts.weapon.position.y += 0.26; parts.weapon.rotation.z = -this.direction * 0.85; parts.armBack.position.x += this.direction * 0.16; parts.armBack.rotation.z = this.direction * 0.21; parts.legLeft.rotation.z = this.direction * 0.1; parts.legRight.rotation.z = -this.direction * 0.1; }
    else if (this.action === "damaged") { const impact = Math.max(0, 1 - elapsed / 0.32); this.root.rotation.z = this.direction * (0.12 + impact * 0.1); this.sprite.position.x = -this.direction * (0.08 + impact * 0.12); parts.torso.position.x = -this.direction * (0.08 + impact * 0.1); parts.armFront.rotation.z = this.direction * 0.45; parts.handFront.position.x -= this.direction * 0.18; parts.weapon.rotation.z = this.direction * 0.56; }
    else if (this.action === "down") { this.root.rotation.z = this.direction * 1.12; this.sprite.position.y = -0.72; parts.armFront.rotation.z = this.direction * 1.06; parts.weapon.rotation.z = this.direction * 1.24; }
    this.shadow.scaling.x = this.action === "down" ? 1.45 : 1.02 - Math.abs(this.sprite.position.y) * 1.18; parts.core.rotation.z = Math.sin(now * 7) * 0.12;
  }
}
