import type { Scene } from "@babylonjs/core/scene";

export type InputAction = "left" | "right" | "strike" | "guard" | "boost" | "special";
export type MechaAction = "idle" | "move" | "strike" | "special" | "guard" | "damaged" | "down";
export type MatchState = "select" | "active" | "round-result" | "match-victory" | "match-defeat";
export type LoadoutKey = string;
export type MissionKey = string;
export type CampaignStage = 1 | 2 | 3;
export type TheatreClass = "frontier" | "foundry" | "vault";
export type SurfaceKind = "riveted" | "rail" | "grate" | "cargo" | "magnetic" | "obsidian";
export type ChassisKind = "balanced" | "heavy" | "scout" | "bulwark" | "winged" | "raider" | "brute" | "warden" | "phantom" | "crown";
export type SpecialKind = "lunge" | "fortify" | "blink" | "slam" | "volley";
export type UnlockKind = "starter" | "salvage" | "reward";

export interface SpecialDefinition { key: string; name: string; tactical: string; kind: SpecialKind; damageMultiplier: number; range: number; cooldown: number; }
export type ComboInput = "strike" | "special";
export interface ComboRoute { label: string; sequence: ComboInput[]; finisher: string; tactical: string; window: number; finisherMultiplier: number; }
export interface FrameUnlock { kind: UnlockKind; cost?: number; level?: number; }
export interface MechaProfile { key: LoadoutKey; label: string; callsign: string; maxHp: number; speed: number; strikeDamage: number; guardMultiplier: number; frameScale: number; accent: string; flare: string; description: string; chassis: ChassisKind; special?: SpecialDefinition; unlock?: FrameUnlock; collection?: string; }
export interface AiTuning { aggression: number; attackInterval: number; guardChance: number; pursuitRange: number; }
export interface LocationDefinition { key: string; label: string; callout: string; surface: SurfaceKind; accent: string; atmosphere: string; }
export interface BossDefinition { key: string; title: string; designation: string; transmission: string; directive: string; profile: MechaProfile; artUrl: string; accent: string; behavior: string; }
export interface MissionDefinition { key: MissionKey; code: string; title: string; stage: CampaignStage; stageLabel: string; level: number; theatre: string; objective: string; reward: number; difficulty: number; theatreClass: TheatreClass; location: LocationDefinition; backgroundUrl: string; enemyArtUrl: string; opponent: MechaProfile; ai: AiTuning; boss?: BossDefinition; }

const s = (key: string, name: string, tactical: string, kind: SpecialKind, damageMultiplier: number, range: number, cooldown: number): SpecialDefinition => ({ key, name, tactical, kind, damageMultiplier, range, cooldown });
const f = (key: string, label: string, callsign: string, maxHp: number, speed: number, strikeDamage: number, guardMultiplier: number, frameScale: number, accent: string, flare: string, description: string, chassis: ChassisKind, special: SpecialDefinition, unlock: FrameUnlock, collection: string): MechaProfile => ({ key, label, callsign, maxHp, speed, strikeDamage, guardMultiplier, frameScale, accent, flare, description, chassis, special, unlock, collection });
const r = (label: string, sequence: ComboInput[], finisher: string, tactical: string, window: number, finisherMultiplier: number): ComboRoute => ({ label, sequence, finisher, tactical, window, finisherMultiplier });

export const LOADOUTS: Record<LoadoutKey, MechaProfile> = {
  vanguard: f("vanguard", "AEGIS RIFT", "PILOT-01", 100, 3.45, 15, 0.25, 1, "#236ee2", "#38eaff", "Rail-saber assault frame with twin cyan vector thrusters.", "balanced", s("prism-breaker", "PRISM BREAKER", "Guard-piercing rail-saber lunge.", "lunge", 1.68, 3.35, 2.7), { kind: "starter" }, "SCRAPLINE"),
  ironclad: f("ironclad", "IRONCLAD BASTION", "PILOT-03", 125, 2.75, 17, 0.18, 1.12, "#54748a", "#e6bd58", "Plated breach chassis with a reinforced kinetic shield array.", "heavy", s("bastion-crash", "BASTION CRASH", "Armored crash with a sustained kinetic guard.", "fortify", 1.8, 2.55, 3.35), { kind: "salvage", cost: 480 }, "SCRAPLINE"),
  sparkrunner: f("sparkrunner", "SPARKRUNNER ARC", "PILOT-07", 85, 4.3, 13, 0.33, 0.9, "#38a5ca", "#7de8d0", "Relay hunter with a forked antenna crest and evasive frame.", "scout", s("arc-shift", "ARC SHIFT", "Vector blink into a close-range slash.", "blink", 1.42, 4.15, 2.25), { kind: "salvage", cost: 520 }, "SCRAPLINE"),
  bulwark: f("bulwark", "BULWARK-9", "PILOT-11", 142, 2.38, 20, 0.15, 1.2, "#65777d", "#ffbe3b", "Siege interceptor with fortress shoulders and a cutter arm.", "bulwark", s("citadel-hammer", "CITADEL HAMMER", "Wide shockwave ground slam.", "slam", 2.14, 3.05, 3.7), { kind: "reward", level: 3 }, "SCRAPLINE"),
  pulsewing: f("pulsewing", "PULSEWING NOVA", "PILOT-14", 92, 4.05, 16, 0.28, 0.94, "#446bd1", "#69e7ff", "Wing-fin combat frame built around booster precision.", "winged", s("nova-volley", "NOVA VOLLEY", "Long-reach wing-fin blast volley.", "volley", 1.56, 4.65, 3.1), { kind: "salvage", cost: 620 }, "SCRAPLINE"),
  scrapjack: f("scrapjack", "SCRAPJACK MAUL", "FRAME-18", 118, 2.92, 18, 0.21, 1.06, "#a45c2d", "#f3a84e", "Cargo-yard bruiser carrying a chained impact mace.", "brute", s("chainfall", "CHAINFALL", "Mace-drop that punishes a guarded line.", "slam", 1.91, 3.18, 3.45), { kind: "reward", level: 2 }, "SCRAPLINE"),
  linewarden: f("linewarden", "LINE WARDEN", "FRAME-20", 110, 3.18, 16, 0.2, 1.04, "#647c5b", "#c3e06c", "Frontier security frame with a broad field shield.", "warden", s("rail-lock", "RAIL LOCK", "Shield-rush that fortifies after contact.", "fortify", 1.72, 2.7, 3.1), { kind: "salvage", cost: 450 }, "SCRAPLINE"),
  gildedglaive: f("gildedglaive", "GILDED GLAIVE", "FRAME-25", 94, 3.82, 17, 0.27, 0.98, "#ba8b36", "#ffe07b", "Salvage aristocrat frame with a narrow electro-glaive.", "balanced", s("sun-lance", "SUN LANCE", "Long gold-blade charge through open space.", "lunge", 1.7, 3.58, 2.82), { kind: "reward", level: 5 }, "SCRAPLINE"),
  coalghost: f("coalghost", "COAL GHOST", "FRAME-29", 82, 4.46, 14, 0.34, 0.88, "#4b5158", "#b8d9e8", "Low-signature underpass skirmisher with cold exhaust vents.", "phantom", s("blackout-step", "BLACKOUT STEP", "Ghost blink that slips past pursuit range.", "blink", 1.46, 4.28, 2.18), { kind: "salvage", cost: 720 }, "SCRAPLINE"),
  latchrevenant: f("latchrevenant", "LATCH REVENANT", "FRAME-33", 102, 3.4, 17, 0.25, 1, "#8c4c39", "#f3815a", "Hook-arm recovery frame rebuilt from frontier wreckage.", "raider", s("recovery-hook", "RECOVERY HOOK", "Hooked lunge that punishes retreating frames.", "lunge", 1.64, 3.42, 2.75), { kind: "reward", level: 7 }, "SCRAPLINE"),
  cinderfist: f("cinderfist", "CINDER FIST", "FRAME-41", 128, 2.88, 19, 0.18, 1.1, "#b54a2a", "#ffad4b", "Foundry breaker with a furnace-fed hydraulic fist.", "brute", s("furnace-drop", "FURNACE DROP", "Heavy molten fist slam with wide pressure.", "slam", 2.08, 3.2, 3.62), { kind: "reward", level: 8 }, "FOUNDRY"),
  meltwing: f("meltwing", "MELTWING-4", "FRAME-44", 88, 4.18, 15, 0.3, 0.93, "#d26c34", "#ffcf69", "Heat-shear interceptor with split furnace wings.", "winged", s("slag-volley", "SLAG VOLLEY", "A fan of heat shots from wing furnaces.", "volley", 1.59, 4.48, 3.04), { kind: "salvage", cost: 760 }, "FOUNDRY"),
  aetheranvil: f("aetheranvil", "AETHER ANVIL", "FRAME-48", 136, 2.62, 20, 0.16, 1.16, "#6d657e", "#bba6ff", "Polarity platform frame with a suspended anvil core.", "bulwark", s("polarity-crush", "POLARITY CRUSH", "Magnetic body-check that leaves a hard guard active.", "fortify", 1.87, 2.78, 3.42), { kind: "reward", level: 10 }, "FOUNDRY"),
  voltcarver: f("voltcarver", "VOLT CARVER", "FRAME-52", 96, 3.9, 17, 0.26, 0.98, "#8456a8", "#84ecff", "Coil-disc duelist that carves quick arcs through conductor rails.", "scout", s("coil-shear", "COIL SHEAR", "Blink cut charged by a conductor burst.", "blink", 1.5, 4.1, 2.32), { kind: "salvage", cost: 900 }, "FOUNDRY"),
  kilnregent: f("kilnregent", "KILN REGENT", "FRAME-56", 116, 3.02, 18, 0.2, 1.07, "#663c31", "#f1bd59", "Furnace court frame with a ceremonial cleaver and vent crown.", "heavy", s("regent-cleave", "REGENT CLEAVE", "A heated cleaver rush that fractures guard timing.", "lunge", 1.78, 3.3, 2.96), { kind: "reward", level: 12 }, "FOUNDRY"),
  railbornoracle: f("railbornoracle", "RAILBORN ORACLE", "FRAME-61", 99, 3.74, 17, 0.24, 1, "#73899c", "#d9fbff", "Recovered sentinel with a high antenna lattice and data lance.", "warden", s("signal-lance", "SIGNAL LANCE", "Reactive lance volley with extended signal reach.", "volley", 1.62, 4.52, 3.16), { kind: "reward", level: 15 }, "VAULT"),
  hushvector: f("hushvector", "HUSH VECTOR", "FRAME-64", 84, 4.52, 14, 0.35, 0.88, "#29373c", "#9ff8e4", "Silent vault infiltrator with folded fin thrusters.", "phantom", s("silent-cut", "SILENT CUT", "Fast blink strike that breaks a distant lock.", "blink", 1.48, 4.35, 2.12), { kind: "salvage", cost: 1120 }, "VAULT"),
  starlingsiege: f("starlingsiege", "STARLING SIEGE", "FRAME-68", 132, 2.74, 20, 0.17, 1.15, "#7e3437", "#ffd58f", "Vault breach hauler with a compact starhammer arm.", "bulwark", s("starhammer", "STARHAMMER", "Shockwave slam that locks the combat lane.", "slam", 2.16, 3.12, 3.78), { kind: "reward", level: 17 }, "VAULT"),
  relicsun: f("relicsun", "RELIC SUN", "FRAME-71", 108, 3.48, 18, 0.22, 1.04, "#d2b06e", "#fff1ab", "Recovered gold-and-ivory relic frame with a halo reactor.", "balanced", s("solar-arc", "SOLAR ARC", "Halo-fed saber arc that extends a clean hit.", "lunge", 1.74, 3.55, 2.84), { kind: "salvage", cost: 1300 }, "VAULT"),
  sunforgeprime: f("sunforgeprime", "SUNFORGE PRIME", "FRAME-77", 120, 3.22, 19, 0.19, 1.09, "#d6a83d", "#ffffff", "Legendary relay champion rebuilt after the Crown collapse.", "crown", s("dawn-accord", "DAWN ACCORD", "Crown-class radiant volley through the final corridor.", "volley", 1.76, 4.78, 3.26), { kind: "reward", level: 20 }, "LEGACY"),
};

export const COMBO_ROUTES: Record<LoadoutKey, ComboRoute> = {
  vanguard: r("RAIL TRIAD", ["strike", "strike", "special"], "PRISM BREAKER", "Two cuts prime a guard-piercing lunge.", 1.45, 1.28), ironclad: r("BASTION SEQUENCE", ["strike", "special", "strike"], "BREACH HAMMER", "Crash through pressure, then punish from a fortified stance.", 1.62, 1.34), sparkrunner: r("ARC CASCADE", ["special", "strike", "strike"], "RELAY RIPOSTE", "Blink in first, then accelerate through a two-hit punish.", 1.22, 1.3), bulwark: r("SIEGE CYCLE", ["strike", "strike", "special"], "CITADEL COLLAPSE", "Heavy cuts set up a shockwave finisher.", 1.72, 1.42), pulsewing: r("NOVA WEAVE", ["strike", "special", "strike"], "SKYLINE BURST", "Thread a wing volley between blades.", 1.34, 1.33),
  scrapjack: r("HOOK AND DROP", ["strike", "special", "strike"], "WRECKING DROP", "Chain pressure into a mace finish.", 1.58, 1.36), linewarden: r("GUARD RAIL", ["special", "strike", "strike"], "LOCKDOWN", "Shield entry closes a measured line.", 1.48, 1.31), gildedglaive: r("GILDED EDGE", ["strike", "strike", "special"], "SUN LANCE", "Clean blade cadence becomes a charging finisher.", 1.4, 1.32), coalghost: r("COLD CIRCUIT", ["special", "strike", "strike"], "NIGHT RIP", "Blink around the target then strike twice.", 1.18, 1.29), latchrevenant: r("TETHER BREAK", ["strike", "special", "strike"], "HOOKLINE RUIN", "Hook strike pulls momentum into a final smash.", 1.47, 1.35),
  cinderfist: r("FURNACE BEAT", ["strike", "strike", "special"], "MOLTEN COLLAPSE", "Two furnace punches set a ground rupture.", 1.63, 1.41), meltwing: r("SLAG FEATHER", ["special", "strike", "strike"], "FIRELINE BURST", "Volley pressure opens a fast wing punish.", 1.27, 1.33), aetheranvil: r("POLARITY LOOP", ["strike", "special", "strike"], "ANVIL LOCK", "Magnetise the lane, then close it with force.", 1.68, 1.4), voltcarver: r("COIL CHAIN", ["special", "strike", "strike"], "ARC GUILLOTINE", "Slip the guard and carve a charged exit line.", 1.26, 1.32), kilnregent: r("CROWN OF ASH", ["strike", "strike", "special"], "REGENT FALL", "Ceremonial cuts end in a superheated cleave.", 1.55, 1.38),
  railbornoracle: r("ORACLE LOOP", ["strike", "special", "strike"], "SIGNAL VERDICT", "Data-lance read converts into a far finisher.", 1.42, 1.34), hushvector: r("VOID THREAD", ["special", "strike", "strike"], "HUSH RIPOSTE", "Disappear through pressure and return on the blind side.", 1.17, 1.31), starlingsiege: r("COMET LOCK", ["strike", "strike", "special"], "STARHAMMER FALL", "Absorb the lane then collapse it with the hammer.", 1.71, 1.43), relicsun: r("HALO CIRCUIT", ["strike", "special", "strike"], "RELIC DAWN", "Halo charge turns a saber flow into light.", 1.46, 1.36), sunforgeprime: r("DAWN PROTOCOL", ["special", "strike", "strike"], "SOLAR HORIZON", "A relay volley ignites a final champion route.", 1.38, 1.4),
};

const STAGE_BACKGROUNDS: Record<TheatreClass, string> = { frontier: "/manus-storage/stage-one-scrapyard-dawn_c2c9282f.png", foundry: "/manus-storage/stage-two-cinder-foundry_0ec1dcff.png", vault: "/manus-storage/stage-three-night-vault_f0020e9b.png" };

const STAGE_META: Record<CampaignStage, { label: string; theatre: string; theatreClass: TheatreClass; enemy: MechaProfile; enemyArtUrl: string; boss: BossDefinition; titles: string[]; objectives: string[]; locations: LocationDefinition[] }> = {
  1: { label: "STAGE I // SCRAPLINE FRONTIER", theatre: "SCRAPYARD DAWN", theatreClass: "frontier", enemyArtUrl: "/manus-storage/ember-wraith-custom-frame_75ff79a0.png", enemy: f("rail-raider", "RAIL RAIDER", "ENEMY-01", 108, 3.15, 15, 0.28, 1, "#c92832", "#ff7b26", "Crimson rail patrol chassis armed with a heated plasma blade.", "raider", s("redline-rush", "REDLINE RUSH", "Short plasma-blade rush.", "lunge", 1.3, 2.8, 3.1), { kind: "starter" }, "HOSTILE"), boss: { key: "ember-wraith", title: "EMBER WRAITH", designation: "RAILHEAD EXECUTIONER", transmission: "YOU TOOK THE RAILS. NOW PAY THE FURNACE TAX.", directive: "FRONTIER COMMAND", artUrl: "/manus-storage/ember-wraith-custom-frame_75ff79a0.png", accent: "ember", behavior: "Hook-blade rushes and delayed plasma guard traps.", profile: f("ember-wraith", "EMBER WRAITH", "BOSS-07", 166, 3.36, 20, 0.2, 1.16, "#b92932", "#ff6e2c", "Locomotive-chested Railhead commander carrying twin heated hook blades.", "raider", s("furnace-tax", "FURNACE TAX", "Twin hook rush that burns through the center line.", "lunge", 2.05, 3.65, 3.4), { kind: "starter" }, "BOSS") }, titles: ["RAILHEAD BREACH", "SALVAGE BARRAGE", "DUSTLINE DUEL", "CRANELOCK", "TOWER CIRCUIT", "MOONLIT SCRAP", "FRONTIER COMMAND"], objectives: ["Break the first hostile rail patrol.", "Secure the salvage lane before convoy dawn.", "Disable a raider escort on the dustline.", "Hold the cargo crane junction.", "Capture the cyan relay tower.", "Survive the moonlit scrap ambush.", "Defeat the Scrapline commander."], locations: [{ key: "railspire", label: "RAILSPIRE YARD", callout: "RIVETED TRANSFER DECK", surface: "rail", accent: "#39e5dd", atmosphere: "dawn" }, { key: "salvage-sluice", label: "SALVAGE SLUICE", callout: "CARGO MAGLINE", surface: "cargo", accent: "#f1bd4a", atmosphere: "dust" }, { key: "dustline", label: "DUSTLINE UNDERPASS", callout: "COAL PLATE GANTRY", surface: "riveted", accent: "#ffad68", atmosphere: "haze" }, { key: "cranespine", label: "CRANESPINE JUNCTION", callout: "SUSPENDED SERVICE RAIL", surface: "rail", accent: "#61cddd", atmosphere: "highwind" }, { key: "tower-grid", label: "RELAY TOWER GRID", callout: "ELECTRIC ACCESS DECK", surface: "grate", accent: "#58eff1", atmosphere: "ion" }, { key: "moonfall", label: "MOONFALL DEPOT", callout: "LUNAR SCRAP PLATFORM", surface: "cargo", accent: "#c9a5ee", atmosphere: "night" }, { key: "frontier-gate", label: "FRONTIER GATEHOUSE", callout: "COMMAND RAIL PLATFORM", surface: "riveted", accent: "#ff8a47", atmosphere: "alarm" }] },
  2: { label: "STAGE II // CINDER FOUNDRY", theatre: "CINDER FOUNDRY", theatreClass: "foundry", enemyArtUrl: "/manus-storage/warden-helix-boss-frame_114334d4.png", enemy: f("foundry-guard", "FOUNDRY GUARD", "ENEMY-22", 126, 3.28, 18, 0.22, 1.08, "#733f45", "#f1a95b", "Heat-shield security frame running the furnace floor.", "warden", s("heat-wall", "HEAT WALL", "Braced heat shield response.", "fortify", 1.35, 2.5, 3.3), { kind: "starter" }, "HOSTILE"), boss: { key: "warden-helix", title: "WARDEN HELIX", designation: "FOUNDRY OVERSIGHT INTELLIGENCE", transmission: "ALL UNAUTHORIZED FRAMES WILL BE MELTED INTO THE LINE.", directive: "CINDER FOUNDRY", artUrl: "/manus-storage/warden-helix-boss-frame_114334d4.png", accent: "helix", behavior: "Magnetic defense halo, hard guards, and molten counter bursts.", profile: f("warden-helix", "WARDEN HELIX", "BOSS-14", 194, 3.12, 23, 0.16, 1.22, "#5d3a82", "#ffb45d", "Foundry intelligence commander with a revolving hard-light guard halo.", "warden", s("helix-lock", "HELIX LOCK", "Rotating guard halo that collapses the lane.", "fortify", 2.18, 3.1, 3.7), { kind: "starter" }, "BOSS") }, titles: ["FURNACE GATE", "CHAINFALL", "HEAT SINK", "SMELTER RUN", "ASHEN RELAY", "MAGNETIC CRUCIBLE", "FOUNDRY OVERSEER"], objectives: ["Open the sealed furnace gate.", "Break the chain-lift security patrol.", "Secure the coolant-control heat sink.", "Outrun the smelter line commander.", "Claim the ashen relay uplink.", "Survive the magnetic crucible shift.", "Defeat the Foundry overseer."], locations: [{ key: "furnace-arch", label: "FURNACE ARCH", callout: "HEAT-SHIELDED GRATE", surface: "grate", accent: "#ff9a45", atmosphere: "furnace" }, { key: "chainfall", label: "CHAINFALL LIFT", callout: "VERTICAL CARGO DECK", surface: "cargo", accent: "#ffc354", atmosphere: "sparks" }, { key: "coolant-basin", label: "COOLANT BASIN", callout: "CONDENSER SERVICE PLATE", surface: "riveted", accent: "#6de8ff", atmosphere: "steam" }, { key: "smelter-run", label: "SMELTER RUN", callout: "MOVING POUR LINE", surface: "rail", accent: "#ff7652", atmosphere: "molten" }, { key: "ashen-relay", label: "ASHEN RELAY", callout: "CINDER SIGNAL DECK", surface: "grate", accent: "#ffbc5d", atmosphere: "ash" }, { key: "magnetic-crucible", label: "MAGNETIC CRUCIBLE", callout: "POLARITY PLATFORM", surface: "magnetic", accent: "#b281ff", atmosphere: "arc" }, { key: "overseer-dais", label: "OVERSEER DAIS", callout: "FOUNDRY COMMAND FLOOR", surface: "riveted", accent: "#72e6ff", atmosphere: "lockdown" }] },
  3: { label: "FINAL STAGE // NIGHT VAULT", theatre: "NIGHT VAULT", theatreClass: "vault", enemyArtUrl: "/manus-storage/zero-crown-final-boss-frame_f74aa26d.png", enemy: f("vault-sentinel", "VAULT SENTINEL", "ENEMY-66", 148, 3.44, 21, 0.19, 1.18, "#4a3745", "#cf75a8", "Obsidian security frame carrying a shield blade and node crown.", "crown", s("vault-rend", "VAULT REND", "Obsidian blade volley response.", "volley", 1.45, 3.8, 3.3), { kind: "starter" }, "HOSTILE"), boss: { key: "zero-crown", title: "ZERO CROWN", designation: "NIGHT VAULT CATASTROPHE ENGINE", transmission: "YOU DID NOT BREAK THE CROWN. YOU ACTIVATED IT.", directive: "NIGHT VAULT", artUrl: "/manus-storage/zero-crown-final-boss-frame_f74aa26d.png", accent: "crown", behavior: "Shield-blade parries, crown pulses, and precision vault counters.", profile: f("zero-crown", "ZERO CROWN", "BOSS-20", 232, 3.58, 26, 0.13, 1.28, "#9d2948", "#ff69c2", "Catastrophe engine with an obsidian shield cloak and reactor crown.", "crown", s("crown-fall", "CROWN FALL", "Crown pulse that reaches the full vault lane.", "volley", 2.28, 4.4, 3.9), { kind: "starter" }, "BOSS") }, titles: ["BLACKSITE ENTRY", "SECURITY ECLIPSE", "VAULT HEART", "CROWN PROTOCOL", "ZERO HOUR", "THE FINAL LINK"], objectives: ["Breach the first Night Vault security line.", "Disable the eclipse relay defenses.", "Claim the vault-heart reactor channel.", "Break the CROWN protocol guard network.", "Survive the final zero-hour barrage.", "Defeat ZERO CROWN and secure the campaign."], locations: [{ key: "blacksite-bridge", label: "BLACKSITE BRIDGE", callout: "OBSIDIAN LINKWAY", surface: "obsidian", accent: "#ff73c5", atmosphere: "eclipse" }, { key: "eclipse-array", label: "ECLIPSE ARRAY", callout: "SURVEILLANCE SPINE", surface: "grate", accent: "#9f8eff", atmosphere: "void" }, { key: "vault-heart", label: "VAULT HEART", callout: "REACTOR CORE RING", surface: "magnetic", accent: "#64f5ec", atmosphere: "reactor" }, { key: "crown-protocol", label: "CROWN PROTOCOL CHAMBER", callout: "COMMAND SIGIL DECK", surface: "obsidian", accent: "#ff68b7", atmosphere: "protocol" }, { key: "zero-hour-dock", label: "ZERO HOUR DOCK", callout: "FINAL MAGLOCK FLOOR", surface: "rail", accent: "#ffa668", atmosphere: "breach" }, { key: "crown-apex", label: "CROWN APEX", callout: "NIGHT VAULT THRONE DECK", surface: "obsidian", accent: "#ff58bc", atmosphere: "apex" }] },
};

const makeLevel = (level: number): MissionDefinition => {
  const stage: CampaignStage = level <= 7 ? 1 : level <= 14 ? 2 : 3;
  const index = stage === 1 ? level - 1 : stage === 2 ? level - 8 : level - 15;
  const meta = STAGE_META[stage];
  const boss = index === meta.titles.length - 1 ? meta.boss : undefined;
  const source = boss?.profile ?? meta.enemy;
  const opponent = { ...source, maxHp: source.maxHp + (boss ? 0 : (level - 1) * 8), speed: Number((source.speed + (boss ? 0 : (level - 1) * 0.035)).toFixed(2)), strikeDamage: source.strikeDamage + (boss ? 0 : Math.floor((level - 1) / 3)), guardMultiplier: boss ? source.guardMultiplier : Math.max(0.11, Number((source.guardMultiplier - (level - 1) * 0.004).toFixed(2))) };
  return { key: `level-${String(level).padStart(2, "0")}`, code: `LVL-${String(level).padStart(2, "0")}`, title: meta.titles[index], stage, stageLabel: meta.label, level, theatre: meta.theatre, objective: meta.objectives[index], reward: 210 + level * 85 + (boss ? 380 : 0), difficulty: level, theatreClass: meta.theatreClass, location: meta.locations[index], backgroundUrl: STAGE_BACKGROUNDS[meta.theatreClass], enemyArtUrl: boss?.artUrl ?? meta.enemyArtUrl, opponent, ai: { aggression: Number((0.3 + level * 0.03 + (boss ? 0.13 : 0)).toFixed(2)), attackInterval: Math.max(0.31, Number((1.1 - level * 0.032 - (boss ? 0.09 : 0)).toFixed(2))), guardChance: Math.min(0.68, Number((0.12 + level * 0.02 + (boss ? 0.1 : 0)).toFixed(2))), pursuitRange: Math.max(1.5, Number((2.45 - level * 0.035).toFixed(2))) }, boss };
};

export const CAMPAIGN_LEVELS = Array.from({ length: 20 }, (_, index) => makeLevel(index + 1));
export const MISSIONS: Record<MissionKey, MissionDefinition> = Object.fromEntries(CAMPAIGN_LEVELS.map((mission) => [mission.key, mission]));

export interface HudState { playerHp: number; playerMaxHp: number; enemyHp: number; enemyMaxHp: number; playerState: MechaAction; enemyState: MechaAction; playerX: number; enemyX: number; matchState: MatchState; round: number; playerRounds: number; enemyRounds: number; playerLabel: string; playerCallsign: string; enemyLabel: string; enemyCallsign: string; selectedLoadout: LoadoutKey; missionKey: MissionKey; missionTitle: string; missionObjective: string; missionReward: number; missionLevel: number; stage: CampaignStage; stageLabel: string; theatreClass: TheatreClass; locationKey: string; locationLabel: string; locationCallout: string; surface: SurfaceKind; locationAccent: string; atmosphere: string; backgroundUrl: string; enemyArtUrl: string; soundOn: boolean; combo: number; overdrive: boolean; specialCooldown: number; specialReady: boolean; routeLabel: string; routeStep: number; routeLength: number; routeNextInput: ComboInput; routeFinisherArmed: boolean; counterStatus: string; message: string; }
export interface GameHandle { scene: Scene; update: (delta: number) => void; setAction: (action: InputAction, pressed: boolean) => void; startMatch: (loadout: LoadoutKey, mission: MissionKey) => void; returnToSelect: () => void; toggleAudio: () => boolean; dispose: () => void; }
